eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
