eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

server:
  port: 8090

spring:
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: egt-app
            client-secret: secret
            redirect-uri: "http://localhost:8091/login/oauth2/code/<registrationId>"
            scope: read,write
        provider:
          custom-provider:
            authorization-uri: http://localhost:8080/oauth/authorize
            token-uri: http://localhost:8080/oauth/token
            user-info-uri: http://localhost:8080/userinfo
            user-name-attribute: neehar

spring:
  cloud:
    gateway:
      routes:
        - id: egt-user-service
          uri: lb://egt-user-service
          predicates:
            - Path=/egt-user-service/**
          filters:
            - RewritePath=/egt-user-service/(?<path>.*), /$\{path}
