eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/oauth2/jwks
  cloud:
    gateway:
      routes:
        - id: egt-user-service
          uri: lb://egt-user-service
          predicates:
            - Path=/egt-user-service/**
          filters:
            - RewritePath=/egt-user-service/(?<path>.*), /$\{path}
