eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    register-with-eureka: true
  instance:
    preferIpAddress: false
    hostname: localhost

server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: egt-user-service
          uri: localhost:8091
          predicates:
            - Path=/egt-user-service/**
